### PR TITLE
Add devs and ibm-qnlp past events

### PR DESCRIPTION
**Pull request by AdithyaSireesh**
[Add Devs screening and IBM event to past events #41
](https://github.com/Dan5762/Imperial-Quantum-Society/issues/41)

- Added devs images and text description (had to resize images)
- Added ibm qnlp images and description
- Removed IBM talk from upcoming events

### CODE REVIEW

**Comment by AdithyaSireesh** [comment]
Screenshot 2022-07-03 at 21 43 18

**Comment by h-rathee851** [comment]
QNLP sizing is a bit wonky. 
Screen Shot 2022-07-03 at 9 44 50 pm

**Comment by AdithyaSireesh** [comment]
I need to double check this, but i was kinda forced to resize to a 1:1 aspect ratio. If not, then the images wouldn't fit the whole area

**Comment by h-rathee851** [comment]
yeah a 1:1 aspect ratio is good. I was thinking something where the text box for the whole list sizes according to the largest one.

**Comment by AdithyaSireesh** [comment]
Reduced the text length to a little less than the multiverse event description. So, should be good to go

**Pull request merged**
